Repository mr-robot-2008/js, pull requests merged in 2022-10, with the labels that each got.

#1 color-changing-app in Js for hacktoberfest 2022
  color-changing-app-main/color-changing-app-main/README.md
  color-changing-app-main/color-changing-app-main/app.js
  color-changing-app-main/color-changing-app-main/index.html
  color-changing-app-main/color-changing-app-main/style.css
Labels: hacktoberfest2022

#5 Update CONTRIBUTION.md
  CONTRIBUTION.md
Labels: hacktoberfest2022

#4 given a list of 0's, 1's and 2's are sorted
  code/Given a linked list of 0s, 1s and 2s, sort it.cpp
Labels: hacktoberfest 2022 accepted

#6 Create Prime number.java
  code/Prime number.java
Labels: hacktoberfest 2022 accepted

#7 Create Selection sort
  code/Selection Sort.cpp
Labels: hacktoberfest2022

#8 Added Project and edited CONTRIBUTION file
  CONTRIBUTION.md
  SimpleCalculator/CSS/style.css
  SimpleCalculator/HTML/index.html
  SimpleCalculator/IMG/calculatorTitle.png
  SimpleCalculator/JS/script.js
  SimpleCalculator/README.md
Labels: hacktoberfest2022

#10 Create merge sort.cpp
  merge sort.cpp
Labels: Hacktoberfest

#9 Create factorial.java
  CONTRIBUTION.md
  factorial.java
Labels: Hacktoberfest

#12 add a random number
  random number.cpp
Labels: Hacktoberfest

#15 array in java
  Array.java
  CONTRIBUTION.md
Labels: hacktoberfest 2022 accepted

#11 added a program to check and delete loop inside in linked list
  checkingAndDeletingLoopInLinkedList.c
Labels: Hacktoberfest

#13 C++ program to demonstrate Fibonacci heap
  code/Fibonacci_Heap.cpp
Labels: Hacktoberfest

#19 Update README.md
  README.md
Labels: Hacktoberfest

#22 Create fillingbucket.cpp
  fillingbucket.cpp
Labels: Hacktoberfest

#23 jssnakegame
  CONTRIBUTION.md
  JSgame.js
Labels: Hacktoberfest

#16 Create heapsort.java
  heapsort.java
Labels: Hacktoberfest

#21 BLUE.js
  BLUE.js
Labels: Hacktoberfest

#14 solution of kth larget element in array is added
  3sumSolution.cpp
  Kth_larget_element_in_array.cpp
Labels: Hacktoberfest

#24 perfectsquare.js
  perfectsquare.js
Labels: Hacktoberfest

#26 fibonacci.js
  fibonacci.js
Labels: Hacktoberfest

#27 quadratic.js
  quadratic.js
Labels: Hacktoberfest

#29 hacktoberfest2022
  quadraticequation.js
Labels: Hacktoberfest

#28 Create pyramid.cpp
  pyramid.cpp
Labels: Hacktoberfest

#30 Update CONTRIBUTION.md
  CONTRIBUTION.md
Labels: Hacktoberfest

#31 Added Java Codes
  code/Age Calculator.java
  code/AllCharactersToLowerCase.java
  code/Area of Circle.java
  code/ArrayElementBinarySearch.java
  code/ArrayList.java
  code/ArrayListExample.java
  code/ArrayinReverseOrder.java
Labels: Hacktoberfest

#32 Create Palindrome Java program
  Palindrome Java program
Labels: Hacktoberfest

#33 Created Js reverse a string code
  Js reverse a string code
Labels: Hacktoberfest

#36 Create code.js
  code.js
Labels: Hacktoberfest

#37 Create programme.js
  programme.js
Labels: Hacktoberfest

#41 Add Palindrome validation
  CONTRIBUTION.md
  Palindrome/index.html
Labels: Hacktoberfest

#40 remove consecutive character
  Remove Consecutive Characters.js
Labels: Hacktoberfest

#39 Create program.js
  program.js
Labels: Hacktoberfest

#42 Patch 2
  CONTRIBUTION.md
  adjacentElements.js
Labels: Hacktoberfest

#43 Update README.md
  README.md
Labels: Hacktoberfest

#46 Create merge linked list.java
  merge linked list.java
Labels: Hacktoberfest

#50 Create array.js
  array.js
Labels: Hacktoberfest, hacksquad

#51 Create Maximum sum of non-adjacent elements
  Maximum sum of non-adjacent elements
Labels: Hacktoberfest, hacksquad

#57 Create html.html
  html.html
Labels: Hacktoberfest, hacksquad

#58 Create cal.css
  cal.css
Labels: Hacktoberfest, hacksquad

#59 Create cal.js
  cal.js
Labels: Hacktoberfest, hacksquad

#60 Create todo.html
  todo.html
Labels: Hacktoberfest, hacksquad

#61 Create todo.css
  todo.css
Labels: Hacktoberfest, hacksquad

#62 Create todo.js
  todo.js
Labels: Hacktoberfest, hacksquad

#25 maxSubArray
  maxSubArray.js
Labels: Hacktoberfest

#66 Add files via upload
  Missingnumber.py
Labels: Hacktoberfest

#67 Add files via upload
  Mergesort.py
Labels: Hacktoberfest

#68 Create swap.js
  swap.js
Labels: Hacktoberfest

#71 numgen
  numgen.js
Labels: Hacktoberfest

#69 Create creaing_digital_clk.js
  creaing_digital_clk.js
Labels: Hacktoberfest

#70 Add Survey Form
  SurveyForm/README.md
  SurveyForm/Screenshot (61).png
  SurveyForm/index.html
  SurveyForm/main.js
Labels: Hacktoberfest

#72 countdowntimer javascript code
  countdowntimer.html
Labels: Hacktoberfest

#74 Create Check for BST.cpp
  Check for BST.cpp
Labels: hacktoberfest 2022 accepted, Hacktoberfest

#77 Create binary.cpp
  binary.cpp
Labels: Hacktoberfest

#76 Pascal'sTriange.cpp
  Pascal'sTriange.cpp
Labels: Hacktoberfest
