Repository mr-robot-2008/js, pull requests merged in 2023-10, with the labels that each got.

#82 Create calculator.java
  calculator.java
Labels: hacktoberfest2022, hacktoberfest 2022 accepted

#83 Create kth.js
  kth.js
Labels: hacktoberfest2022, hacktoberfest 2022 accepted, Hacktoberfest, hacktoberfest-accepted

#84 Create Divide_two_integers_without_using_multiplication,_division_and…
  Divide_two_integers_without_using_multiplication,_division_and_mod_operator.py
Labels: hacktoberfest2022, hacktoberfest 2022 accepted, Hacktoberfest, hacktoberfest-accepted

#86 Create progress_bar.js
  progress_bar.js
Labels: hacktoberfest2022, hacktoberfest 2022 accepted, Hacktoberfest, hacktoberfest-accepted

#89 Create todo_application.js
  todo_application.js
Labels: hacktoberfest2022, hacktoberfest 2022 accepted, Hacktoberfest, hacktoberfest-accepted

#88 Create theatre_animation.js
  theatre_animation.js
Labels: hacktoberfest2022, hacktoberfest 2022 accepted, Hacktoberfest, hacktoberfest-accepted

#87 Create garbage_dump_truck_animation.js
  garbage_dump_truck_animation.js
Labels: hacktoberfest2022, hacktoberfest 2022 accepted, Hacktoberfest, hacktoberfest-accepted

#85 Create knapsack.js
  knapsack.js
Labels: hacktoberfest2022, hacktoberfest 2022 accepted, Hacktoberfest, hacktoberfest-accepted

#91 Create Profile.js
  Profile.js
Labels: hacktoberfest2022, hacktoberfest 2022 accepted, Hacktoberfest, hacktoberfest-accepted

#90 Create Modern-login-page.js
  Modern-login-page.js
Labels: hacktoberfest2022, hacktoberfest 2022 accepted, Hacktoberfest, hacktoberfest-accepted

#95 Create Delete_Button.js
  Delete_Button.js
Labels: hacktoberfest2022, hacktoberfest 2022 accepted, Hacktoberfest, hacktoberfest-accepted

#94 Create Spotlight_Cursor.js
  Spotlight_Cursor.js
Labels: hacktoberfest2022, hacktoberfest 2022 accepted, Hacktoberfest

#93 Create Vertical_Timeline.js
  Vertical_Timeline.js
Labels: invalid

#96 Create agecalculator.js
  agecalculator.js
Labels: hacktoberfest2022, hacktoberfest 2022 accepted, Hacktoberfest, hacktoberfest-accepted

#101 Create FibonacciSeries.js
  FibonacciSeries.js
Labels: hacktoberfest2022, hacktoberfest 2022 accepted, Hacktoberfest, hacktoberfest-accepted

#100 Create InsertionSort.py
  InsertionSort.py
Labels: hacktoberfest2022, hacktoberfest 2022 accepted, Hacktoberfest, hacktoberfest-accepted

#97 Create grid_stragering.js
  grid_stragering.js
Labels: bug, invalid

#98 Create Number_counter_animation.js
  Number_counter_animation.js
Labels: hacktoberfest2022, hacktoberfest 2022 accepted, hacktoberfest-accepted

#102 Create Tearable_Cloth.js
  Tearable_Cloth.js
Labels: hacktoberfest2022, hacktoberfest 2022 accepted, Hacktoberfest, hacktoberfest-accepted

#104 Create SelectionSort.c
  SelectionSort.c
Labels: hacktoberfest2022, hacktoberfest 2022 accepted, Hacktoberfest, hacktoberfest-accepted

#103 Create BinarySearch.c
  BinarySearch.c
Labels: hacktoberfest2022, hacktoberfest 2022 accepted, Hacktoberfest, hacktoberfest-accepted

#105 Create calcuJS
  calcuJS
Labels: hacktoberfest2022, hacktoberfest 2022 accepted, Hacktoberfest, hacktoberfest-accepted

#106 Create permutationofstring.py
  permutationofstring.py
Labels: hacktoberfest2022, hacktoberfest 2022 accepted, Hacktoberfest, hacktoberfest-accepted

#107 Added coinChange file
  coinChange.js
Labels: hacktoberfest2022, hacktoberfest 2022 accepted, Hacktoberfest, hacktoberfest-accepted

#108 add dice simulator
  Dice Simulator/Dice_Simulator.java
Labels: hacktoberfest2022, hacktoberfest 2022 accepted, Hacktoberfest, hacktoberfest-accepted

#111 Leetcode Maximum Subarray Problem Solution
  Max_Subarray.py
Labels: hacktoberfest2022, hacktoberfest 2022 accepted, Hacktoberfest, hacktoberfest-accepted

#112 added 2D array wave print file
  2D-Array-Wave-Print.js
Labels: hacktoberfest2022, hacktoberfest 2022 accepted, Hacktoberfest, hacktoberfest-accepted

#113 Create Minimum number of Coins .cpp
  Minimum number of Coins .cpp
Labels: hacktoberfest2022, hacktoberfest 2022 accepted, Hacktoberfest, hacktoberfest-accepted

#114 Random Quote Genrator
  Random_Qutote_Genrator/index.html
  Random_Qutote_Genrator/script.js
  Random_Qutote_Genrator/styles.css
Labels: hacktoberfest2022, hacktoberfest 2022 accepted, Hacktoberfest, hacktoberfest-accepted

#118 Create logo_animation.js
  logo_animation.js
Labels: hacktoberfest2022, hacktoberfest 2022 accepted, Hacktoberfest, hacktoberfest-accepted

#117 Create expanding_grid_item_animation.js
  expanding_grid_item_animation.js
Labels: hacktoberfest2022, hacktoberfest 2022 accepted, Hacktoberfest, hacktoberfest-accepted

#116 Create mobile_planet_gallery.js
  mobile_planet_gallery.js
Labels: hacktoberfest2022, hacktoberfest 2022 accepted, Hacktoberfest, hacktoberfest-accepted

#115 Create Animated_cycle.js
  Animated_cycle.js
Labels: hacktoberfest2022, hacktoberfest 2022 accepted, Hacktoberfest, hacktoberfest-accepted

#122 Create binarysearch.js
  binarysearch.js
Labels: hacktoberfest2022, hacktoberfest 2022 accepted, Hacktoberfest, hacktoberfest-accepted

#121 Adi03tya/dnf sort
  code/DNF-Sort.js
  code/palindrome-string.js
Labels: hacktoberfest2022, hacktoberfest 2022 accepted, Hacktoberfest, hacktoberfest-accepted

#123 CHOCOLATE DISTRIBUTION PROBLEM'S SOLUTION
  Chocolate_Distribution.py
Labels: hacktoberfest2022, hacktoberfest 2022 accepted, Hacktoberfest, hacktoberfest-accepted

#131 Create calc.js
  calc.js
Labels: hacktoberfest2022, hacktoberfest 2022 accepted, Hacktoberfest, hacktoberfest-accepted

#130 Create slide-in.js
  slide-in.js
Labels: hacktoberfest2022, hacktoberfest 2022 accepted, Hacktoberfest, hacktoberfest-accepted

#129 Create n_d.js
  n_d.js
Labels: hacktoberfest2022, hacktoberfest 2022 accepted, Hacktoberfest, hacktoberfest-accepted

#128 Create guess-the-num.js
  guess-the-num.js
Labels: hacktoberfest2022, hacktoberfest 2022 accepted, Hacktoberfest, hacktoberfest-accepted
